// export const ActionTypes = {
//   SET_PRODUCTS: "SET_PRUDUCTS",
//   SELECTED_PRODUCT: "SELECTED_PRODUCT",
//   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
//   INCREMENT: "INCREMENT",
//   DECREMENT: "DECREMENT",
//   LOADING: "LOADING",
// };
